[workspace]
members = ["contracts/*", "packages/*"]

[profile.release.package.pfc-steak]
opt-level = 3
debug = true
debug-assertions = true
codegen-units = 1
incremental = true

[profile.release]
rpath = true
lto = true
overflow-checks = true
